### ISSUE TITLE
last commit version cannot render any graph

### ISSUE THREAD

**Issue by vaab** [facette/facette#243] opened 2015-08-03 06:21 UTC
I had graph working with the previous image (probably from ``docker pull facette/facette``). I did a fresh build of the docker image, had to change some permission settings in ``/var/lib/facette``, and all seem to work... except all graphing: 

```
2015/08/03 06:16:36 http: panic serving 172.17.42.1:51877: runtime error: invalid memory address or nil pointer dereference
goroutine 1091 [running]:
net/http.func·011()
        /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/facette/facette/pkg/connector.(*RRDConnector).GetPlots(0xc208098680, 0xc2083e82d0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/connector/rrd.go:99 +0xe12
github.com/facette/facette/pkg/server.executeQueries(0xc208387e00, 0xc2080c60c0, 0x0, 0x0)
        /facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:290 +0x11d
github.com/facette/facette/pkg/server.(*Server).servePlots(0xc2080c6000, 0x7fc50d5f23e0, 0xc208352ea0, 0xc208356f70)
        /facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:109 +0xf77
github.com/facette/facette/pkg/server.*Server.(github.com/facette/facette/pkg/server.servePlots)·fm(0x7fc50d5f23e0, 0xc208352ea0, 0xc208356f70)
        /facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/worker_serve.go:58 +0x45
net/http.HandlerFunc.ServeHTTP(0xc2080f81a0, 0x7fc50d5f23e0, 0xc208352ea0, 0xc208356f70)
        /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc2081bbec0, 0x7fc50d5f23e0, 0xc208352ea0, 0xc208356f70)
        /usr/local/go/src/net/http/server.go:1541 +0x17d
github.com/facette/facette/pkg/server.(*Router).ServeHTTP(0xc2080f8160, 0x7fc50d5f2380, 0xc20802e780, 0xc208356f70)
        /facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/router.go:44 +0x153
net/http.(*ServeMux).ServeHTTP(0xc208038ba0, 0x7fc50d5f2380, 0xc20802e780, 0xc208356f70)
        /usr/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc208245020, 0x7fc50d5f2380, 0xc20802e780, 0xc208356f70)
        /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20802e3c0)
        /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x35e
```

As you can infer in the traceback, I'm using the RRD connector. Do you need any more information ?

**Comment by vbatoufflet** [comment] 2015-08-06 04:49
Hi Valentin,

I will add some tests to prevent the crash but I can't reproduce it.

Can you share your configuration files with us please?

**Comment by vaab** [comment] 2015-08-06 12:19
All my configuration files are bad, even the simplest ones. Take only one metric from one RRD and graph it.

Here's what I can do:

I'm providing a docker image with the latest code (supposedly) on docker.0k.io/facette:latest

So you should be able to reproduce the issue by executing this:
```
docker run -ti -u root --entrypoint /bin/bash -p 12003:12003 docker.0k.io/facette -c '
apt-get -y install rrdtool sudo
cat <<EOF > /etc/facette/providers/collectd.json
{
    "connector": {
        "type": "rrd",
        "path": "/tmp/rrd",
        "pattern": "(?P<source>[^/]+)/(?P<metric>.+).rrd"
    }
}
EOF
mkdir -p /tmp/rrd/s1
rrdtool create /tmp/rrd/s1/test.rrd --start N --step 300 DS:probe1-temp:GAUGE:600:55:95 RRA:AVERAGE:0.5:1:1440
sudo -u daemon facette
'
```

This creates a simple providers that connects to a single empty RRD. You should be able to log in ``localhost:12003``, and create a graph, add Origin:``collectd``, Source:``s1``, Metric:``test/probe1-temp/average``, it should make a traceback when previewing the result.

And if it is my docker code the culprit, I just built it with:
```
docker build -t docker.0k.io/facette:latest https://github.com/facette/facette.git
```

**Comment by vbatoufflet** [comment] 2015-08-07 06:27
Thanks for the information. I will take a look at it.

**Comment by kiranos** [comment] 2015-08-12 07:59
Hi I have git cloned the most recent master and seem to have the same issue:

very basic install on debian jessie with packages from official repo. 

When I create a new graph (have zero before) and hit next at the screen which shows:

Administration Panel — New GraphCancel  Previous  Next  Save Graph
Series

I get this error below and no preview of the graphs.

```
2015/08/12 09:56:51 http: panic serving 79.99.4.16:55326: runtime error: invalid memory address or nil pointer dereference
goroutine 347 [running]:
net/http.func·011()
        /usr/lib/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x7f4d60, 0xc7f253)
        /usr/lib/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/facette/facette/pkg/connector.(*RRDConnector).GetPlots(0xc208054100, 0xc208b67d40, 0x0, 0x0, 0x0, 0x0, 0x0)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/connector/rrd.go:99 +0xcea
github.com/facette/facette/pkg/server.executeQueries(0xc209ea2300, 0xc209acc180, 0x0, 0x0)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:290 +0x10b
github.com/facette/facette/pkg/server.(*Server).servePlots(0xc2080560c0, 0x7f25dc60b420, 0xc20a1c2f80, 0xc209ab80d0)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:109 +0xdcb
github.com/facette/facette/pkg/server.*Server.(github.com/facette/facette/pkg/server.servePlots)·fm(0x7f25dc60b420, 0xc20a1c2f80, 0xc209ab80d0)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/worker_serve.go:58 +0x44
net/http.HandlerFunc.ServeHTTP(0xc208203880, 0x7f25dc60b420, 0xc20a1c2f80, 0xc209ab80d0)
        /usr/lib/go/src/pkg/net/http/server.go:1235 +0x40
net/http.(*ServeMux).ServeHTTP(0xc2081fb8c0, 0x7f25dc60b420, 0xc20a1c2f80, 0xc209ab80d0)
        /usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
github.com/facette/facette/pkg/server.(*Router).ServeHTTP(0xc208203840, 0x7f25dc60b3c0, 0xc20a1c4dc0, 0xc209ab80d0)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/router.go:44 +0x11b
net/http.(*ServeMux).ServeHTTP(0xc208024ae0, 0x7f25dc60b3c0, 0xc20a1c4dc0, 0xc209ab80d0)
        /usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc2080fa2a0, 0x7f25dc60b3c0, 0xc20a1c4dc0, 0xc209ab80d0)
        /usr/lib/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc208b72600)
        /usr/lib/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
        /usr/lib/go/src/pkg/net/http/server.go:1721 +0x313
2015/08/12 09:56:51 http: panic serving 79.99.4.16:55328: runtime error: invalid memory address or nil pointer dereference
goroutine 349 [running]:
net/http.func·011()
        /usr/lib/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x7f4d60, 0xc7f253)
        /usr/lib/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/facette/facette/pkg/connector.(*RRDConnector).GetPlots(0xc208054100, 0xc208f18750, 0x0, 0x0, 0x0, 0x0, 0x0)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/connector/rrd.go:99 +0xcea
github.com/facette/facette/pkg/server.executeQueries(0xc2092f4210, 0xc209acc240, 0x0, 0x0)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:290 +0x10b
github.com/facette/facette/pkg/server.(*Server).servePlots(0xc2080560c0, 0x7f25dc60b420, 0xc20926c3a0, 0xc209ab8000)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:109 +0xdcb
github.com/facette/facette/pkg/server.*Server.(github.com/facette/facette/pkg/server.servePlots)·fm(0x7f25dc60b420, 0xc20926c3a0, 0xc209ab8000)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/worker_serve.go:58 +0x44
net/http.HandlerFunc.ServeHTTP(0xc208203880, 0x7f25dc60b420, 0xc20926c3a0, 0xc209ab8000)
        /usr/lib/go/src/pkg/net/http/server.go:1235 +0x40
net/http.(*ServeMux).ServeHTTP(0xc2081fb8c0, 0x7f25dc60b420, 0xc20926c3a0, 0xc209ab8000)
        /usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
github.com/facette/facette/pkg/server.(*Router).ServeHTTP(0xc208203840, 0x7f25dc60b3c0, 0xc20932a3c0, 0xc209ab8000)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/router.go:44 +0x11b
net/http.(*ServeMux).ServeHTTP(0xc208024ae0, 0x7f25dc60b3c0, 0xc20932a3c0, 0xc209ab8000)
        /usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc2080fa2a0, 0x7f25dc60b3c0, 0xc20932a3c0, 0xc209ab8000)
        /usr/lib/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc208b72880)
        /usr/lib/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
        /usr/lib/go/src/pkg/net/http/server.go:1721 +0x313
2015/08/12 09:56:52 http: panic serving 79.99.4.16:55325: runtime error: invalid memory address or nil pointer dereference
goroutine 342 [running]:
net/http.func·011()
        /usr/lib/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x7f4d60, 0xc7f253)
        /usr/lib/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/facette/facette/pkg/connector.(*RRDConnector).GetPlots(0xc208054100, 0xc209e2fb90, 0x0, 0x0, 0x0, 0x0, 0x0)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/connector/rrd.go:99 +0xcea
github.com/facette/facette/pkg/server.executeQueries(0xc208aee990, 0xc209acc300, 0x0, 0x0)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:290 +0x10b
github.com/facette/facette/pkg/server.(*Server).servePlots(0xc2080560c0, 0x7f25dc60b420, 0xc20837c660, 0xc20883c000)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:109 +0xdcb
github.com/facette/facette/pkg/server.*Server.(github.com/facette/facette/pkg/server.servePlots)·fm(0x7f25dc60b420, 0xc20837c660, 0xc20883c000)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/worker_serve.go:58 +0x44
net/http.HandlerFunc.ServeHTTP(0xc208203880, 0x7f25dc60b420, 0xc20837c660, 0xc20883c000)
        /usr/lib/go/src/pkg/net/http/server.go:1235 +0x40
net/http.(*ServeMux).ServeHTTP(0xc2081fb8c0, 0x7f25dc60b420, 0xc20837c660, 0xc20883c000)
        /usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
github.com/facette/facette/pkg/server.(*Router).ServeHTTP(0xc208203840, 0x7f25dc60b3c0, 0xc209b210e0, 0xc20883c000)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/router.go:44 +0x11b
net/http.(*ServeMux).ServeHTTP(0xc208024ae0, 0x7f25dc60b3c0, 0xc209b210e0, 0xc20883c000)
        /usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc2080fa2a0, 0x7f25dc60b3c0, 0xc209b210e0, 0xc20883c000)
        /usr/lib/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc208b72000)
        /usr/lib/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
        /usr/lib/go/src/pkg/net/http/server.go:1721 +0x313
2015/08/12 09:56:52 http: panic serving 79.99.4.16:55327: runtime error: invalid memory address or nil pointer dereference
goroutine 348 [running]:
net/http.func·011()
        /usr/lib/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x7f4d60, 0xc7f253)
        /usr/lib/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/facette/facette/pkg/connector.(*RRDConnector).GetPlots(0xc208054100, 0xc208a54000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/connector/rrd.go:99 +0xcea
github.com/facette/facette/pkg/server.executeQueries(0xc208025fb0, 0xc209acc480, 0x0, 0x0)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:290 +0x10b
github.com/facette/facette/pkg/server.(*Server).servePlots(0xc2080560c0, 0x7f25dc60b420, 0xc20a3a3e40, 0xc20883c1a0)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:109 +0xdcb
github.com/facette/facette/pkg/server.*Server.(github.com/facette/facette/pkg/server.servePlots)·fm(0x7f25dc60b420, 0xc20a3a3e40, 0xc20883c1a0)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/worker_serve.go:58 +0x44
net/http.HandlerFunc.ServeHTTP(0xc208203880, 0x7f25dc60b420, 0xc20a3a3e40, 0xc20883c1a0)
        /usr/lib/go/src/pkg/net/http/server.go:1235 +0x40
net/http.(*ServeMux).ServeHTTP(0xc2081fb8c0, 0x7f25dc60b420, 0xc20a3a3e40, 0xc20883c1a0)
        /usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
github.com/facette/facette/pkg/server.(*Router).ServeHTTP(0xc208203840, 0x7f25dc60b3c0, 0xc20a3a5c20, 0xc20883c1a0)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/router.go:44 +0x11b
net/http.(*ServeMux).ServeHTTP(0xc208024ae0, 0x7f25dc60b3c0, 0xc20a3a5c20, 0xc20883c1a0)
        /usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc2080fa2a0, 0x7f25dc60b3c0, 0xc20a3a5c20, 0xc20883c1a0)
        /usr/lib/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc208b72800)
        /usr/lib/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
        /usr/lib/go/src/pkg/net/http/server.go:1721 +0x313
2015/08/12 09:56:52 http: panic serving 79.99.4.16:55353: runtime error: invalid memory address or nil pointer dereference
goroutine 364 [running]:
net/http.func·011()
        /usr/lib/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x7f4d60, 0xc7f253)
        /usr/lib/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/facette/facette/pkg/connector.(*RRDConnector).GetPlots(0xc208054100, 0xc209478b40, 0x0, 0x0, 0x0, 0x0, 0x0)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/connector/rrd.go:99 +0xcea
github.com/facette/facette/pkg/server.executeQueries(0xc2098f93e0, 0xc209acc240, 0x0, 0x0)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:290 +0x10b
github.com/facette/facette/pkg/server.(*Server).servePlots(0xc2080560c0, 0x7f25dc60b420, 0xc20946fbc0, 0xc209ab8000)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:109 +0xdcb
github.com/facette/facette/pkg/server.*Server.(github.com/facette/facette/pkg/server.servePlots)·fm(0x7f25dc60b420, 0xc20946fbc0, 0xc209ab8000)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/worker_serve.go:58 +0x44
net/http.HandlerFunc.ServeHTTP(0xc208203880, 0x7f25dc60b420, 0xc20946fbc0, 0xc209ab8000)
        /usr/lib/go/src/pkg/net/http/server.go:1235 +0x40
net/http.(*ServeMux).ServeHTTP(0xc2081fb8c0, 0x7f25dc60b420, 0xc20946fbc0, 0xc209ab8000)
        /usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
github.com/facette/facette/pkg/server.(*Router).ServeHTTP(0xc208203840, 0x7f25dc60b3c0, 0xc2094399a0, 0xc209ab8000)
        /var/www/html/facette/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/router.go:44 +0x11b
net/http.(*ServeMux).ServeHTTP(0xc208024ae0, 0x7f25dc60b3c0, 0xc2094399a0, 0xc209ab8000)
        /usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc2080fa2a0, 0x7f25dc60b3c0, 0xc2094399a0, 0xc209ab8000)
        /usr/lib/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc2096dc000)
        /usr/lib/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
        /usr/lib/go/src/pkg/net/http/server.go:1721 +0x313
```

**Comment by vbatoufflet** [comment] 2015-08-14 04:49
@vaab, I can't manage to reproduce the same crash :(
I see how to prevent it and return an error message instead of panicking, but I can't trigger it.

@kiranos, if I get this right you have this error running Facette without using docker?
Can you share with us your configuration?

**Comment by vbatoufflet** [comment] 2015-08-14 05:29
Ok so I figured out what's happening.

This bug was appeared with this fix 4e08b0d3e6f5593eacf0d48a3622a4b6385cccbb.

It's fixed in fb89a1917df568f2c9d9a5877e0694ce832eecf0.

**Closed by vbatoufflet** 2015-08-14 05:29 UTC
Labels: Back-end, Bug

**Comment by kiranos** [comment] 2015-08-14 06:11
nice! thanks I'll give it a spin.

**Comment by vaab** [comment] 2015-08-14 16:41
Perfect, this is working now with the given test and the latest build. Many Thanks.
