### ISSUE TITLE
Unable to save Graph

### ISSUE THREAD

**Issue by DerPate** [facette/facette#179] opened 2015-03-29 12:18 UTC
Hello,

today esting facette i get some strange response. I'm unable to save any kind of Graph nothing happens after pressing the save Graph button. Some output from the debug log bellow:
2015/03/29 14:04:19 DEBUG: serveWorker: "GET /admin/graphs/27756e83-ff4e-48d6-56d9-49ac4a5b57b5 HTTP/1.1" 200
2015/03/29 14:04:20 DEBUG: serveWorker: "GET /api/v1/library/graphs/27756e83-ff4e-48d6-56d9-49ac4a5b57b5 HTTP/1.1" 200
2015/03/29 14:04:21 DEBUG: serveWorker: "GET /api/v1/catalog/origins/?limit=1 HTTP/1.1" 200
2015/03/29 14:04:21 DEBUG: serveWorker: "GET /api/v1/library/sourcegroups/?origin=&limit=1 HTTP/1.1" 200
2015/03/29 14:04:21 DEBUG: serveWorker: "GET /api/v1/catalog/sources/?origin=&limit=1 HTTP/1.1" 200
2015/03/29 14:04:21 DEBUG: serveWorker: "GET /api/v1/catalog/metrics/?origin=&source=&limit=1 HTTP/1.1" 200
2015/03/29 14:04:21 DEBUG: serveWorker: "GET /api/v1/library/metricgroups/?origin=&source=&limit=1 HTTP/1.1" 200
2015/03/29 14:04:24 DEBUG: serveWorker: "GET /api/v1/library/sourcegroups/?origin=my_metrics&filter=glob%3Ade* HTTP/1.1" 200
2015/03/29 14:04:24 DEBUG: serveWorker: "GET /api/v1/catalog/sources/?origin=my_metrics&filter=glob%3Ade* HTTP/1.1" 200
2015/03/29 14:04:28 DEBUG: serveWorker: "GET /api/v1/catalog/metrics/?origin=my_metrics&source=de%2Fdominikbreu.de&filter=glob%3Ado* HTTP/1.1" 200
2015/03/29 14:04:28 DEBUG: serveWorker: "GET /api/v1/library/metricgroups/?origin=my_metrics&source=de%2Fdominikbreu.de&filter=glob%3Ado* HTTP/1.1" 200
2015/03/29 14:04:35 DEBUG: serveWorker: "GET /api/v1/library/metricgroups/?origin=my_metrics&source=de%2Fdominikbreu.de&filter=glob%3Adove* HTTP/1.1" 200
2015/03/29 14:04:35 DEBUG: serveWorker: "GET /api/v1/catalog/metrics/?origin=my_metrics&source=de%2Fdominikbreu.de&filter=glob%3Adove* HTTP/1.1" 200
2015/03/29 14:05:09 DEBUG: serveWorker: "GET /api/v1/library/units/labels HTTP/1.1" 200
2015/03/29 14:05:14 DEBUG: serveWorker: "GET /api/v1/library/units/labels HTTP/1.1" 200
2015/03/29 14:05:18 DEBUG: serveWorker: "POST /api/v1/plots HTTP/1.1" 200
2015/03/29 14:05:22 DEBUG: serveWorker: "POST /api/v1/plots HTTP/1.1" 200
2015/03/29 14:05:26 DEBUG: serveWorker: "POST /api/v1/plots HTTP/1.1" 200
2015/03/29 14:06:18 DEBUG: serveWorker: "POST /api/v1/plots HTTP/1.1" 200
2015/03/29 14:06:21 DEBUG: serveWorker: "POST /api/v1/plots HTTP/1.1" 2
2015/03/29 14:06:37 DEBUG: serveWorker: "POST /api/v1/plots HTTP/1.1" 200

version are
facette -V
facette version 0.4.0dev
Go version: go1.3.3 (gc)

Available connectors:
   facette
   graphite
   influxdb
   kairosdb
   rrd

**Comment by falzm** [comment] 2015-03-29 17:57
Hi Dominik

Do you run facette directly on your system or do you run it via Docker?

**Comment by DerPate** [comment] 2015-03-29 18:15
run direct on my system access it via apache2 version 2.4 proxy

**Comment by falzm** [comment] 2015-03-29 18:21
Can you check that the UID facette is running with has write permissions on the path set for `data_dir` in the configuration file?

**Comment by DerPate** [comment] 2015-03-29 18:25
it runs under root for testing porposse and the folder permission are drwxrwxrwx root:root  the only thing not saved is the graph everthing else get stored

**Comment by falzm** [comment] 2015-03-29 18:36
If "everything else gets stored" that is *really* weird, since is it the **same** code that handles storage for all objects (graphs, collections, metric/source groups, units etc.).

@vbatoufflet, WDYT?

**Comment by vbatoufflet** [comment] 2015-03-29 19:49
Hi Dominik,

Indeed it seems weird, there is no `POST` or `PUT` trace on `/api/v1/library/graphs` in the logs. Traces that should be triggered when creating or updating a graph.

Is there any error in your browser console?

**Comment by vbatoufflet** [comment] 2015-03-29 20:12
I managed to reproduce the issue under Chrome, it seems that event wasn't triggered from the desired DOM element.

It is fixed in 0bbb26f102e69da0e6e74a896e908bf486e9b5db.

**Comment by DerPate** [comment] 2015-03-29 20:57
Thx ! Nice work keep on rocking =) 
Am Sonntag, den 29.03.2015, 13:12 -0700 schrieb Vincent Batoufflet:

**Comment by vbatoufflet** [comment] 2015-03-30 06:32
You're welcome.

This fix will soon be shipped in the 0.3.0 version to come.

**Closed by vbatoufflet** 2015-03-30 06:32 UTC
Labels: Bug, UI
