### ISSUE TITLE
No data in graphs and crash

### ISSUE THREAD

**Issue by faxm0dem** [facette/facette#229] opened 2015-06-30 08:56 UTC
Graphs show no data. Also I can't save graphs.
When trying to load it into the browser, for a "remote" connector I get:

```
WARNING: server: unknown source `' for origin `collectd'
```

And for a local connector I get:

```
2015/06/30 10:32:59 http: panic serving 127.0.0.1:58962: runtime error: invalid memory address or nil pointer dereference
goroutine 333 [running]:
net/http.func·011()
        /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/facette/facette/pkg/connector.(*RRDConnector).GetPlots(0xc208112a80, 0xc20db0a090, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/connector/rrd.go:101 +0x107a
github.com/facette/facette/pkg/server.executeQueries(0xc2223a2000, 0xc222420240, 0x0, 0x0)
        /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:289 +0x11d
github.com/facette/facette/pkg/server.(*Server).servePlots(0xc208079970, 0x7fac5812c308, 0xc2224412a0, 0xc2221656c0)
        /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:109 +0xf77
github.com/facette/facette/pkg/server.*Server.(github.com/facette/facette/pkg/server.servePlots)·fm(0x7fac5812c308, 0xc2224412a0, 0xc2221656c0)
        /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/worker_serve.go:58 +0x45
net/http.HandlerFunc.ServeHTTP(0xc20812c300, 0x7fac5812c308, 0xc2224412a0, 0xc2221656c0)
        /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc208120150, 0x7fac5812c308, 0xc2224412a0, 0xc2221656c0)
        /usr/local/go/src/net/http/server.go:1541 +0x17d
github.com/facette/facette/pkg/server.(*Router).ServeHTTP(0xc20812c2c0, 0x7fac5812c2a8, 0xc20804fae0, 0xc2221656c0)
        /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/router.go:44 +0x153
net/http.(*ServeMux).ServeHTTP(0xc20803cc60, 0x7fac5812c2a8, 0xc20804fae0, 0xc2221656c0)
        /usr/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc208074c00, 0x7fac5812c2a8, 0xc20804fae0, 0xc2221656c0)
        /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20804f4a0)
        /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x35e
2015/06/30 10:33:00 http: panic serving 127.0.0.1:58967: runtime error: invalid memory address or nil pointer dereference
goroutine 350 [running]:
net/http.func·011()
        /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/facette/facette/pkg/connector.(*RRDConnector).GetPlots(0xc208112a80, 0xc20db0a3f0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/connector/rrd.go:101 +0x107a
github.com/facette/facette/pkg/server.executeQueries(0xc2223a2840, 0xc2224203c0, 0x0, 0x0)
        /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:289 +0x11d
github.com/facette/facette/pkg/server.(*Server).servePlots(0xc208079970, 0x7fac5812c308, 0xc222430560, 0xc2221652b0)
        /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:109 +0xf77
github.com/facette/facette/pkg/server.*Server.(github.com/facette/facette/pkg/server.servePlots)·fm(0x7fac5812c308, 0xc222430560, 0xc2221652b0)
        /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/worker_serve.go:58 +0x45
net/http.HandlerFunc.ServeHTTP(0xc20812c300, 0x7fac5812c308, 0xc222430560, 0xc2221652b0)
        /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc208120150, 0x7fac5812c308, 0xc222430560, 0xc2221652b0)
        /usr/local/go/src/net/http/server.go:1541 +0x17d
github.com/facette/facette/pkg/server.(*Router).ServeHTTP(0xc20812c2c0, 0x7fac5812c2a8, 0xc20804fd60, 0xc2221652b0)
        /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/router.go:44 +0x153
net/http.(*ServeMux).ServeHTTP(0xc20803cc60, 0x7fac5812c2a8, 0xc20804fd60, 0xc2221652b0)
        /usr/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc208074c00, 0x7fac5812c2a8, 0xc20804fd60, 0xc2221652b0)
        /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20804e500)
        /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x35e
2015/06/30 10:33:00 http: panic serving 127.0.0.1:58972: runtime error: invalid memory address or nil pointer dereference
goroutine 363 [running]:
net/http.func·011()
        /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/facette/facette/pkg/connector.(*RRDConnector).GetPlots(0xc208112a80, 0xc20db0a750, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/connector/rrd.go:101 +0x107a
github.com/facette/facette/pkg/server.executeQueries(0xc2223a3320, 0xc2224206c0, 0x0, 0x0)
        /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:289 +0x11d
github.com/facette/facette/pkg/server.(*Server).servePlots(0xc208079970, 0x7fac5812c308, 0xc222431880, 0xc222165d40)
        /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/api_plot.go:109 +0xf77
github.com/facette/facette/pkg/server.*Server.(github.com/facette/facette/pkg/server.servePlots)·fm(0x7fac5812c308, 0xc222431880, 0xc222165d40)
        /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/worker_serve.go:58 +0x45
net/http.HandlerFunc.ServeHTTP(0xc20812c300, 0x7fac5812c308, 0xc222431880, 0xc222165d40)
        /usr/local/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc208120150, 0x7fac5812c308, 0xc222431880, 0xc222165d40)
        /usr/local/go/src/net/http/server.go:1541 +0x17d
github.com/facette/facette/pkg/server.(*Router).ServeHTTP(0xc20812c2c0, 0x7fac5812c2a8, 0xc2221360a0, 0xc222165d40)
        /tmp/facette/build/facette-linux-amd64/src/github.com/facette/facette/pkg/server/router.go:44 +0x153
net/http.(*ServeMux).ServeHTTP(0xc20803cc60, 0x7fac5812c2a8, 0xc2221360a0, 0xc222165d40)
        /usr/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc208074c00, 0x7fac5812c2a8, 0xc2221360a0, 0xc222165d40)
        /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc222136000)
        /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x35e
```

Here's my config:

``` JSON
{
        "bind": ":12003",
        "base_dir": "/opt/facette/share/facette",
        "providers_dir": "/opt/etc/facette/providers",
        "data_dir": "/var/lib/facette",
        "pid_file": "/var/run/facette/facette.pid",
        "read_only": false
}
```

``` JSON
{
        "connector": {
                "type": "rrd",
                "path": "/srv/rrd",
                "pattern": "(?P<source>[^/]+)/(?P<metric>.+).rrd"
        },

        "filters": [
        ],

        "daemon": "unix:/var/run/rrdcached/rrdcached.sock",

        "refresh_interval": 0
}
```

``` JSON
{
  "connector": {
    "type": "facette",
    "upstream": "http://otherfacette:12003"
  }
}
```

**Comment by vbatoufflet** [comment] 2015-06-30 09:10
Thanks for your report. I will take a look at it and try to reproduce it on my setup.

-- 
Vincent Batoufflet

**Comment by faxm0dem** [comment] 2015-06-30 09:11
I may have to flush old facette config?

**Comment by vbatoufflet** [comment] 2015-07-01 05:53
That shouldn't be needed. Which version of Facette do you use?

**Comment by faxm0dem** [comment] 2015-07-01 05:56
0.3.0rc1

**Comment by StephaneBunel** [comment] 2015-07-07 08:53
Graphs show no data upgrading to 0.3.0rc1

config.json
```
{
	"bind": "tcp://127.0.0.1:8082",
	"base_dir": "/srv/www/facette/share/facette",
	"data_dir": "/srv/www/facette/data",
	"pid_file": "/var/run/facette/facette.pid",
	"providers_dir": "/srv/www/facette/etc/providers",
	"read_only": false
}
```

providers/collectd.json
```
{
	"connector": {
		"type": "rrd",
		"path": "/srv/collectd/rrd",
		"pattern": "(?P<source>[^/]+[^/]+)/(?P<metric>.+).rrd"
	},

	"filters": [],

	"refresh_interval": 0
}
```

**Comment by vbatoufflet** [comment] 2015-07-07 15:42
@StephaneBunel as we spoke about it via PM the problem came from this change:

https://blog.facette.io/2015/03/23/facette-0-3-0rc1/#supportformultipleconsolidationfunctionsinrrdtoolconnector

@faxm0dem can you confirm that the issue is fixed on your side too?

**Comment by StephaneBunel** [comment] 2015-07-07 16:36
Thank you @vbatoufflet it's ok now with the help of the filter to mimic the old naming convention.

**Comment by vbatoufflet** [comment] 2015-08-14 05:00
Hi @faxm0dem is the issue fixed for you too?

**Comment by faxm0dem** [comment] 2015-08-14 06:57
Sorry I didn't have time to check. I'll try to do this today

**Comment by vbatoufflet** [comment] 2015-08-14 11:36
It seems that the issue was similar to the one in #243.

**Comment by faxm0dem** [comment] 2015-08-14 11:46
the workaround in the config fixes the crash, and graphs are indeed displayed

**Closed** 2017-03-15 15:20 UTC
