### ISSUE TITLE
Panic on graph creation

### ISSUE THREAD

**Issue by enp** [facette/facette#285] opened 2015-12-21 18:10 UTC
It is impossible to create graph via admin interface - output is attached
[facette.txt](https://github.com/facette/facette/files/68822/facette.txt)

**Comment by enp** [comment] 2015-12-21 18:17
Strace output is attached too
[facette-strace.txt](https://github.com/facette/facette/files/68826/facette-strace.txt)

**Comment by falzm** [comment] 2015-12-21 18:22
Hi

Looking at your error log it's more like your Facette instance process got a "segmentation fault" signal following the opening of a RRDtoo file:

```
[pid  3811] open("/var/lib/collectd/eye/cpu/percent-system.rrd", O_RDONLY) = 12
[pid  3811] fstat(12, {st_mode=S_IFREG|0644, st_size=148648, ...}) = 0
[pid  3811] mmap(NULL, 148648, PROT_READ, MAP_PRIVATE|MAP_NORESERVE, 12, 0) = 0x7f3906851000
[pid  3811] madvise(0x7f3906851000, 148648, MADV_RANDOM) = 0
[pid  3811] munmap(0x7f3906851000, 148648) = 0
[pid  3811] close(12)                   = 0
[pid  3811] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
[pid  3811] rt_sigreturn({mask=[]})     = 139882051701392
```

Is it coincidental? Could you try to start Facette excluding the file `/var/lib/collectd/eye/cpu/percent-system.rrd`?

**Comment by enp** [comment] 2015-12-21 18:25
It works on system with kernel 3.14.22 and did not work on system with kernel 4.1.13 (on host system and inside systemd-nspawn container). Both facette instances are extracted from deb into /opt as described in https://github.com/facette/facette/issues/284

**Comment by enp** [comment] 2015-12-21 18:26
Problem is reproducing on all rrd files created by local installed collectd.

**Comment by enp** [comment] 2015-12-21 18:31
Problem is even reproducing on copied rrd files from system with 3.14.22 on which facette works correctly with the same files

**Comment by enp** [comment] 2015-12-21 18:33
Maybe some libraries are missing? I can give ssh access tomorrow into container with panic if it may help.

**Comment by falzm** [comment] 2015-12-21 18:35
Is it possible there is a mismatch between 32 and 64-bit architectures? RRDtool is sensitive to that, although I don't think it would crash the entire program.

**Comment by enp** [comment] 2015-12-21 18:35
All systems are x86_64

**Comment by falzm** [comment] 2015-12-21 18:38
Which versions of Facette and librrd are you using?

**Comment by enp** [comment] 2015-12-21 18:41
```
Build Information
Version: 	0.3.0
Build Date: 	2015-07-08
Compiler: 	gc (go1.4.2)
Built-in Connectors: 	facette
graphite
influxdb
kairosdb
rrd
```

librrd4-1.4.7-alt3.1 on working system and librrd4-1.5.4-alt1.1 on panic

**Comment by falzm** [comment] 2015-12-21 18:46
Looks like the RRDtool binding we rely on (https://github.com/ziutek/rrd) only supports librrd 1.4.x and crashes on 1.5.x, see this issue: https://github.com/ziutek/rrd/issues/24

Unfortunately there is nothing we can do for this particular problem, sorry. Could it be possible to downgrade your librrd to 1.4.x?

**Comment by xor-gate** [comment] 2015-12-21 22:40
This possible a duplicate of #207

**Comment by vbatoufflet** [comment] 2015-12-22 04:39
@enp, have you tried to compile Facette from the sources linking it on the rrd 1.5 library?

**Comment by enp** [comment] 2015-12-22 07:53
Tried now. Version 0.4.0dev (last trunk) allows to create graphs, version 0.3.0 fails with the same output as above. Go version is 1.5.1 in both cases.

**Closed** 2016-08-08 11:08 UTC
Labels: Back-end, Bug, Connector, Third-party
